FROM python:3.10-slim
ENV TZ="Asia/Almaty"
RUN pip install --upgrade pip

COPY requirements/ /tmp/requirements

RUN pip install --no-cache-dir -r /tmp/requirements/dev.txt

RUN useradd -m -d /proj -s /bin/bash app
WORKDIR /proj
COPY .. /proj

ADD https://github.com/amacneil/dbmate/releases/download/v1.6.0/dbmate-linux-musl-amd64 /usr/local/bin/dbmate
RUN chmod +x /usr/local/bin/dbmate

RUN chown -R app:app /proj/*
USER app